; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: %opt %s -S -passes=test-vector-codegen,adce -p add16,add16.1,add16.2,add16.3/pmaddwd128 -p i,i2,i4,i6,i8,i10,i12,i14 -p i1,i3,i5,i7,i9,i11,i13,i15 -p storeOf:add16,storeOf:add16.1,storeOf:add16.2,storeOf:add16.3 -detect-simple-reduction | FileCheck %s
target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-macosx10.15.0"

@a = local_unnamed_addr global [8 x i16] zeroinitializer, align 16
@b = local_unnamed_addr global [8 x i16] zeroinitializer, align 16
@c = local_unnamed_addr global [4 x i32] zeroinitializer, align 16

; CHECK-LABEL: @foo(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[I2_VEC:%.*]] = load <8 x i16>, ptr @a, align 16
; CHECK-NEXT:    [[I3_VEC:%.*]] = load <8 x i16>, ptr @b, align 16
; CHECK-NEXT:    [[BINARY_REDUCER_VEC:%.*]] = call <4 x i32> @llvm.x86.sse2.pmadd.wd(<8 x i16> [[I3_VEC]], <8 x i16> [[I2_VEC]])
; CHECK-NEXT:    store <4 x i32> [[BINARY_REDUCER_VEC]], ptr @c, align 16
; CHECK-NEXT:    ret void

; Function Attrs: nofree norecurse nosync nounwind ssp uwtable
define void @foo() local_unnamed_addr #0 {

entry:
  %i = load i16, ptr @a, align 16, !tbaa !5
  %conv = sext i16 %i to i32
  %i1 = load i16, ptr @b, align 16, !tbaa !5
  %conv4 = sext i16 %i1 to i32
  %mul5 = mul nsw i32 %conv4, %conv
  %i2 = load i16, ptr getelementptr inbounds ([8 x i16], ptr @a, i64 0, i64 1), align 2, !tbaa !5
  %conv9 = sext i16 %i2 to i32
  %i3 = load i16, ptr getelementptr inbounds ([8 x i16], ptr @b, i64 0, i64 1), align 2, !tbaa !5
  %conv14 = sext i16 %i3 to i32
  %mul15 = mul nsw i32 %conv14, %conv9
  %add16 = add nsw i32 %mul15, %mul5
  store i32 %add16, ptr @c, align 16, !tbaa !9
  %i4 = load i16, ptr getelementptr inbounds ([8 x i16], ptr @a, i64 0, i64 2), align 4, !tbaa !5
  %conv.1 = sext i16 %i4 to i32
  %i5 = load i16, ptr getelementptr inbounds ([8 x i16], ptr @b, i64 0, i64 2), align 4, !tbaa !5
  %conv4.1 = sext i16 %i5 to i32
  %mul5.1 = mul nsw i32 %conv4.1, %conv.1
  %i6 = load i16, ptr getelementptr inbounds ([8 x i16], ptr @a, i64 0, i64 3), align 2, !tbaa !5
  %conv9.1 = sext i16 %i6 to i32
  %i7 = load i16, ptr getelementptr inbounds ([8 x i16], ptr @b, i64 0, i64 3), align 2, !tbaa !5
  %conv14.1 = sext i16 %i7 to i32
  %mul15.1 = mul nsw i32 %conv14.1, %conv9.1
  %add16.1 = add nsw i32 %mul15.1, %mul5.1
  store i32 %add16.1, ptr getelementptr inbounds ([4 x i32], ptr @c, i64 0, i64 1), align 4, !tbaa !9
  %i8 = load i16, ptr getelementptr inbounds ([8 x i16], ptr @a, i64 0, i64 4), align 8, !tbaa !5
  %conv.2 = sext i16 %i8 to i32
  %i9 = load i16, ptr getelementptr inbounds ([8 x i16], ptr @b, i64 0, i64 4), align 8, !tbaa !5
  %conv4.2 = sext i16 %i9 to i32
  %mul5.2 = mul nsw i32 %conv4.2, %conv.2
  %i10 = load i16, ptr getelementptr inbounds ([8 x i16], ptr @a, i64 0, i64 5), align 2, !tbaa !5
  %conv9.2 = sext i16 %i10 to i32
  %i11 = load i16, ptr getelementptr inbounds ([8 x i16], ptr @b, i64 0, i64 5), align 2, !tbaa !5
  %conv14.2 = sext i16 %i11 to i32
  %mul15.2 = mul nsw i32 %conv14.2, %conv9.2
  %add16.2 = add nsw i32 %mul15.2, %mul5.2
  store i32 %add16.2, ptr getelementptr inbounds ([4 x i32], ptr @c, i64 0, i64 2), align 8, !tbaa !9
  %i12 = load i16, ptr getelementptr inbounds ([8 x i16], ptr @a, i64 0, i64 6), align 4, !tbaa !5
  %conv.3 = sext i16 %i12 to i32
  %i13 = load i16, ptr getelementptr inbounds ([8 x i16], ptr @b, i64 0, i64 6), align 4, !tbaa !5
  %conv4.3 = sext i16 %i13 to i32
  %mul5.3 = mul nsw i32 %conv4.3, %conv.3
  %i14 = load i16, ptr getelementptr inbounds ([8 x i16], ptr @a, i64 0, i64 7), align 2, !tbaa !5
  %conv9.3 = sext i16 %i14 to i32
  %i15 = load i16, ptr getelementptr inbounds ([8 x i16], ptr @b, i64 0, i64 7), align 2, !tbaa !5
  %conv14.3 = sext i16 %i15 to i32
  %mul15.3 = mul nsw i32 %conv14.3, %conv9.3
  %add16.3 = add nsw i32 %mul15.3, %mul5.3
  store i32 %add16.3, ptr getelementptr inbounds ([4 x i32], ptr @c, i64 0, i64 3), align 4, !tbaa !9
  ret void
}

attributes #0 = { nofree norecurse nosync nounwind ssp uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="penryn" "target-features"="+cx16,+cx8,+fxsr,+mmx,+sahf,+sse,+sse2,+sse3,+sse4.1,+ssse3,+x87" "tune-cpu"="generic" }

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"PIC Level", i32 2}
!2 = !{i32 7, !"uwtable", i32 2}
!3 = !{i32 7, !"frame-pointer", i32 2}
!4 = !{!"clang version 15.0.0 (https://github.com/llvm/llvm-project 12f9c7b27063a4a487621f48c167e4f88de6d297)"}
!5 = !{!6, !6, i64 0}
!6 = !{!"short", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
!9 = !{!10, !10, i64 0}
!10 = !{!"int", !7, i64 0}
