; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: %opt %s -S -passes=global-slp | FileCheck %s
; ModuleID = 's441.c'
source_filename = "s441.c"
target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-macosx10.15.0"

@d = local_unnamed_addr global [32000 x float] zeroinitializer, align 16
@b = local_unnamed_addr global [32000 x float] zeroinitializer, align 16
@c = local_unnamed_addr global [32000 x float] zeroinitializer, align 16
@a = local_unnamed_addr global [32000 x float] zeroinitializer, align 16
@e = local_unnamed_addr global [32000 x float] zeroinitializer, align 16

; Function Attrs: nofree norecurse nosync nounwind ssp uwtable
define void @s278() local_unnamed_addr #0 {
; CHECK-LABEL: @s278(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[DOTVEC:%.*]] = load <4 x float>, ptr @d, align 16
; CHECK-NEXT:    [[CMP1_1_VEC:%.*]] = fcmp olt <4 x float> [[DOTVEC]], zeroinitializer
; CHECK-NEXT:    [[CMP10_1_VEC:%.*]] = fcmp oeq <4 x float> [[DOTVEC]], zeroinitializer
; CHECK-NEXT:    [[TMP0:%.*]] = xor <4 x i1> [[CMP1_1_VEC]], <i1 true, i1 true, i1 true, i1 true>
; CHECK-NEXT:    [[TMP1:%.*]] = xor <4 x i1> [[CMP10_1_VEC]], <i1 true, i1 true, i1 true, i1 true>
; CHECK-NEXT:    [[TMP2:%.*]] = and <4 x i1> [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[DOTVEC1:%.*]] = load <4 x float>, ptr @c, align 16
; CHECK-NEXT:    [[MUL25_1_VEC:%.*]] = fmul <4 x float> [[DOTVEC1]], [[DOTVEC1]]
; CHECK-NEXT:    [[TMP3:%.*]] = and <4 x i1> [[TMP0]], [[CMP10_1_VEC]]
; CHECK-NEXT:    [[DOTVEC2:%.*]] = load <4 x float>, ptr @b, align 16
; CHECK-NEXT:    [[MUL16_1_VEC:%.*]] = fmul <4 x float> [[DOTVEC2]], [[DOTVEC2]]
; CHECK-NEXT:    [[DOTVEC3:%.*]] = load <4 x float>, ptr @b, align 16
; CHECK-NEXT:    [[DOTVEC4:%.*]] = load <4 x float>, ptr @c, align 16
; CHECK-NEXT:    [[MUL_1_VEC:%.*]] = fmul <4 x float> [[DOTVEC4]], [[DOTVEC3]]
; CHECK-NEXT:    [[TMP4:%.*]] = select <4 x i1> [[TMP2]], <4 x float> [[MUL25_1_VEC]], <4 x float> [[MUL_1_VEC]]
; CHECK-NEXT:    [[MUL_1_SINK_VEC:%.*]] = select <4 x i1> [[TMP3]], <4 x float> [[MUL16_1_VEC]], <4 x float> [[TMP4]]
; CHECK-NEXT:    [[DOTVEC5:%.*]] = load <4 x float>, ptr @a, align 16
; CHECK-NEXT:    [[ADD_1_VEC:%.*]] = fadd <4 x float> [[DOTVEC5]], [[MUL_1_SINK_VEC]]
; CHECK-NEXT:    store <4 x float> [[ADD_1_VEC]], ptr @a, align 16
; CHECK-NEXT:    ret void
;
entry:
  %0 = load float, ptr @d, align 16, !tbaa !5
  %cmp1 = fcmp fast olt float %0, 0.000000e+00
  br i1 %cmp1, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %1 = load float, ptr @b, align 16, !tbaa !5
  %2 = load float, ptr @c, align 16, !tbaa !5
  %mul = fmul fast float %2, %1
  br label %for.inc

if.else:                                          ; preds = %entry
  %cmp10 = fcmp fast oeq float %0, 0.000000e+00
  br i1 %cmp10, label %if.then11, label %if.else20

if.then11:                                        ; preds = %if.else
  %3 = load float, ptr @b, align 16, !tbaa !5
  %mul16 = fmul fast float %3, %3
  br label %for.inc

if.else20:                                        ; preds = %if.else
  %4 = load float, ptr @c, align 16, !tbaa !5
  %mul25 = fmul fast float %4, %4
  br label %for.inc

for.inc:                                          ; preds = %if.then, %if.else20, %if.then11
  %mul.sink = phi float [ %mul, %if.then ], [ %mul25, %if.else20 ], [ %mul16, %if.then11 ]
  %5 = load float, ptr @a, align 16, !tbaa !5
  %add = fadd fast float %5, %mul.sink
  store float %add, ptr @a, align 16, !tbaa !5
  %6 = load float, ptr getelementptr inbounds ([32000 x float], ptr @d, i64 0, i64 1), align 4, !tbaa !5
  %cmp1.1 = fcmp fast olt float %6, 0.000000e+00
  br i1 %cmp1.1, label %if.then.1, label %if.else.1

if.else.1:                                        ; preds = %for.inc
  %cmp10.1 = fcmp fast oeq float %6, 0.000000e+00
  br i1 %cmp10.1, label %if.then11.1, label %if.else20.1

if.else20.1:                                      ; preds = %if.else.1
  %7 = load float, ptr getelementptr inbounds ([32000 x float], ptr @c, i64 0, i64 1), align 4, !tbaa !5
  %mul25.1 = fmul fast float %7, %7
  br label %for.inc.1

if.then11.1:                                      ; preds = %if.else.1
  %8 = load float, ptr getelementptr inbounds ([32000 x float], ptr @b, i64 0, i64 1), align 4, !tbaa !5
  %mul16.1 = fmul fast float %8, %8
  br label %for.inc.1

if.then.1:                                        ; preds = %for.inc
  %9 = load float, ptr getelementptr inbounds ([32000 x float], ptr @b, i64 0, i64 1), align 4, !tbaa !5
  %10 = load float, ptr getelementptr inbounds ([32000 x float], ptr @c, i64 0, i64 1), align 4, !tbaa !5
  %mul.1 = fmul fast float %10, %9
  br label %for.inc.1

for.inc.1:                                        ; preds = %if.then.1, %if.then11.1, %if.else20.1
  %mul.1.sink = phi float [ %mul.1, %if.then.1 ], [ %mul16.1, %if.then11.1 ], [ %mul25.1, %if.else20.1 ]
  %11 = load float, ptr getelementptr inbounds ([32000 x float], ptr @a, i64 0, i64 1), align 4, !tbaa !5
  %add.1 = fadd fast float %11, %mul.1.sink
  store float %add.1, ptr getelementptr inbounds ([32000 x float], ptr @a, i64 0, i64 1), align 4, !tbaa !5
  %12 = load float, ptr getelementptr inbounds ([32000 x float], ptr @d, i64 0, i64 2), align 8, !tbaa !5
  %cmp1.2 = fcmp fast olt float %12, 0.000000e+00
  br i1 %cmp1.2, label %if.then.2, label %if.else.2

if.else.2:                                        ; preds = %for.inc.1
  %cmp10.2 = fcmp fast oeq float %12, 0.000000e+00
  br i1 %cmp10.2, label %if.then11.2, label %if.else20.2

if.else20.2:                                      ; preds = %if.else.2
  %13 = load float, ptr getelementptr inbounds ([32000 x float], ptr @c, i64 0, i64 2), align 8, !tbaa !5
  %mul25.2 = fmul fast float %13, %13
  br label %for.inc.2

if.then11.2:                                      ; preds = %if.else.2
  %14 = load float, ptr getelementptr inbounds ([32000 x float], ptr @b, i64 0, i64 2), align 8, !tbaa !5
  %mul16.2 = fmul fast float %14, %14
  br label %for.inc.2

if.then.2:                                        ; preds = %for.inc.1
  %15 = load float, ptr getelementptr inbounds ([32000 x float], ptr @b, i64 0, i64 2), align 8, !tbaa !5
  %16 = load float, ptr getelementptr inbounds ([32000 x float], ptr @c, i64 0, i64 2), align 8, !tbaa !5
  %mul.2 = fmul fast float %16, %15
  br label %for.inc.2

for.inc.2:                                        ; preds = %if.then.2, %if.then11.2, %if.else20.2
  %mul.2.sink = phi float [ %mul.2, %if.then.2 ], [ %mul16.2, %if.then11.2 ], [ %mul25.2, %if.else20.2 ]
  %17 = load float, ptr getelementptr inbounds ([32000 x float], ptr @a, i64 0, i64 2), align 8, !tbaa !5
  %add.2 = fadd fast float %17, %mul.2.sink
  store float %add.2, ptr getelementptr inbounds ([32000 x float], ptr @a, i64 0, i64 2), align 8, !tbaa !5
  %18 = load float, ptr getelementptr inbounds ([32000 x float], ptr @d, i64 0, i64 3), align 4, !tbaa !5
  %cmp1.3 = fcmp fast olt float %18, 0.000000e+00
  br i1 %cmp1.3, label %if.then.3, label %if.else.3

if.else.3:                                        ; preds = %for.inc.2
  %cmp10.3 = fcmp fast oeq float %18, 0.000000e+00
  br i1 %cmp10.3, label %if.then11.3, label %if.else20.3

if.else20.3:                                      ; preds = %if.else.3
  %19 = load float, ptr getelementptr inbounds ([32000 x float], ptr @c, i64 0, i64 3), align 4, !tbaa !5
  %mul25.3 = fmul fast float %19, %19
  br label %for.inc.3

if.then11.3:                                      ; preds = %if.else.3
  %20 = load float, ptr getelementptr inbounds ([32000 x float], ptr @b, i64 0, i64 3), align 4, !tbaa !5
  %mul16.3 = fmul fast float %20, %20
  br label %for.inc.3

if.then.3:                                        ; preds = %for.inc.2
  %21 = load float, ptr getelementptr inbounds ([32000 x float], ptr @b, i64 0, i64 3), align 4, !tbaa !5
  %22 = load float, ptr getelementptr inbounds ([32000 x float], ptr @c, i64 0, i64 3), align 4, !tbaa !5
  %mul.3 = fmul fast float %22, %21
  br label %for.inc.3

for.inc.3:                                        ; preds = %if.then.3, %if.then11.3, %if.else20.3
  %mul.3.sink = phi float [ %mul.3, %if.then.3 ], [ %mul16.3, %if.then11.3 ], [ %mul25.3, %if.else20.3 ]
  %23 = load float, ptr getelementptr inbounds ([32000 x float], ptr @a, i64 0, i64 3), align 4, !tbaa !5
  %add.3 = fadd fast float %23, %mul.3.sink
  store float %add.3, ptr getelementptr inbounds ([32000 x float], ptr @a, i64 0, i64 3), align 4, !tbaa !5
  ret void
}

attributes #0 = { nofree norecurse nosync nounwind ssp uwtable "approx-func-fp-math"="true" "frame-pointer"="all" "min-legal-vector-width"="0" "no-infs-fp-math"="true" "no-nans-fp-math"="true" "no-signed-zeros-fp-math"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="penryn" "target-features"="+cx16,+cx8,+fxsr,+mmx,+sahf,+sse,+sse2,+sse3,+sse4.1,+ssse3,+x87" "tune-cpu"="generic" "unsafe-fp-math"="true" }

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"PIC Level", i32 2}
!2 = !{i32 7, !"uwtable", i32 2}
!3 = !{i32 7, !"frame-pointer", i32 2}
!4 = !{!"clang version 15.0.0 (https://github.com/llvm/llvm-project 12f9c7b27063a4a487621f48c167e4f88de6d297)"}
!5 = !{!6, !6, i64 0}
!6 = !{!"float", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
