; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: %opt -S -passes=test-vector-codegen,adce %s -rdx-to-pack=add5 -rdx-width=2 -disable-reduction-packing | FileCheck %s

source_filename = "rdx.c"
target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-macosx10.15.0"

; CHECK-LABEL: @sum(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[I:%.*]] = load i32, ptr [[A:%.*]], align 4, !tbaa [[TBAA5:![0-9]+]]
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 1
; CHECK-NEXT:    [[I1:%.*]] = load i32, ptr [[ARRAYIDX1]], align 4, !tbaa [[TBAA5]]
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 2
; CHECK-NEXT:    [[I2:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4, !tbaa [[TBAA5]]
; CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 3
; CHECK-NEXT:    [[I3:%.*]] = load i32, ptr [[ARRAYIDX4]], align 4, !tbaa [[TBAA5]]
; CHECK-DAG:     [[TMP0:%.*]] = add i32 [[I]], [[I2]]
; CHECK-DAG:     [[TMP1:%.*]] = add i32 [[I1]], [[I3]]
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <2 x i32> undef, i32 [[TMP0]], i64 0
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <2 x i32> [[TMP2]], i32 [[TMP1]], i64 1
; CHECK-NEXT:    [[TMP4:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP3]])
; CHECK-NEXT:    ret i32 [[TMP4]]

; Function Attrs: argmemonly mustprogress nofree norecurse nosync nounwind readonly ssp willreturn uwtable
define i32 @sum(ptr nocapture noundef readonly %a) local_unnamed_addr #0 {
entry:
  %i = load i32, ptr %a, align 4, !tbaa !5
  %arrayidx1 = getelementptr inbounds i32, ptr %a, i64 1
  %i1 = load i32, ptr %arrayidx1, align 4, !tbaa !5
  %add = add nsw i32 %i, %i1
  %arrayidx2 = getelementptr inbounds i32, ptr %a, i64 2
  %i2 = load i32, ptr %arrayidx2, align 4, !tbaa !5
  %add3 = add nsw i32 %add, %i2
  %arrayidx4 = getelementptr inbounds i32, ptr %a, i64 3
  %i3 = load i32, ptr %arrayidx4, align 4, !tbaa !5
  %add5 = add nsw i32 %add3, %i3
  ret i32 %add5
}

attributes #0 = { argmemonly mustprogress nofree norecurse nosync nounwind readonly ssp willreturn uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="penryn" "target-features"="+cx16,+cx8,+fxsr,+mmx,+sahf,+sse,+sse2,+sse3,+sse4.1,+ssse3,+x87" "tune-cpu"="generic" }

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"PIC Level", i32 2}
!2 = !{i32 7, !"uwtable", i32 2}
!3 = !{i32 7, !"frame-pointer", i32 2}
!4 = !{!"clang version 15.0.0 (https://github.com/llvm/llvm-project 12f9c7b27063a4a487621f48c167e4f88de6d297)"}
!5 = !{!6, !6, i64 0}
!6 = !{!"int", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
